### ISSUE TITLE
Migration Unable to install

### ISSUE THREAD

**Issue by matthewhutchings** [czemu/nova-calendar-tool#1]
Error: Method Illuminate\Database\Schema\Blueprint::id does not exist.

Solution: change     $table->id(); to $table->bigIncrements('id');

**Comment by czemu** [comment]
Hello,

It seems you are using an older Laravel version. Referring to the current (7.x) docs, the method id() exists and is an alias for the bigIncrements('id') method:
https://laravel.com/docs/7.x/migrations#columns

Thank you for sharing your solution!
