### ISSUE TITLE
Change time display from 12h(am/pm) to 24h

### ISSUE THREAD

**Issue by NowakAdmin** [czemu/nova-calendar-tool#3]
I didn't found way to change display of events time. 

I can add them in 24h format, but they display on tool only on 12h format.

There should be also a setting to assign colours to calendars and mayby a format of display event row.

And also view dropdown should be add above calendar like "day", "week", "month" 

And it seems that package is not Translatable i tried create /resources/lang/vendor/czemu and put there my lang pl.json but its not loaded, i also have in /resources/lang/vendor/novapl.json  translated names of month and its not used by package.

**Comment by czemu** [comment]
Thanks, I'll add 24h time format soon.

The calendar translation should be done by using the `locale` option of FullCalendar package. I'll also add the ability to configure it.

**Comment by czemu** [comment]
Both of these things have been added in [version 1.2.0](https://github.com/czemu/nova-calendar-tool/releases/tag/1.2.0).

To change the FullCalendar language, you have to publish the config file:

```
php artisan vendor:publish --provider='Czemu\NovaCalendarTool\ToolServiceProvider' --tag="config"
```

and set it in the published file (usually `app/config/nova-calendar-tool.php`):

```
<?php

return [
    // Calendar language (more info: https://fullcalendar.io/docs/locale)
    'fullcalendar_locale' => 'pl'
];
```
