### ISSUE TITLE
Events not showing

### ISSUE THREAD

**Issue by Waterdhavian** [czemu/nova-calendar-tool#4]
I installed with composer, ran the migration and updated my NovaServiceProvider. _(Not using google calendar for now, that would be my next step to get up and running)_
I do see the Calendar appearing the sidebar and clicking it does take me to the calendar.
However when i add an event by clicking on a day and add an appointment, it does get saved to the database, start and end are filled correctly. But refreshing the page does not show my event in the calendar.

I use the latest version of this module, laravel v7.28.3, laravel nova is set to '*' which is pointed to dev-master. 
Ran composer update as well and tried again but did not change anything.

If you need more information let me know.

**Comment by czemu** [comment]
What do you see in the console on the calendar page? Does the `GET /nova-vendor/nova-calendar-tool/events` request fail?

**Comment by Waterdhavian** [comment]
Yes it does, i had to disable APP_DEBUG in my .env file. The JSON with the events had debug data attached to it, making it an invalid json.

**Comment by czemu** [comment]
This package doesn't depend on the APP_DEBUG variable and doesn't add any debug data to the events json. I think something is wrong with your Laravel setup and unfortunately I can't reproduce this.

**Comment by meletisf** [comment]
I found the issue. 

The `index()` method returns the json data as a standard HTML response and therefore Debugbar injects it's own code inside the payload. If you disable debugbar you will be able to see the events. 

Fixed in #8
