### ISSUE TITLE
Requset: add other views like day and week

### ISSUE THREAD

**Issue by fh32000** [czemu/nova-calendar-tool#6]
Thanks for this nice package @flakerimi @czemu 
It would be nice if you could view the content on a weekly and daily

سيكون من الرائع لو تمكنت من عرض محتوى أسبوعي ويومي
<a href="https://ibb.co/QkZKbdT"><img src="https://i.ibb.co/ypDQfSZ/Show-weekends.png" alt="Show-weekends" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/7rXncnT/ff1.png" alt="ff1" border="0"></a>

**Comment by czemu** [comment]
Hi,

Thanks for your suggestion. I've added week and day view types in version [1.3.0](https://github.com/czemu/nova-calendar-tool/releases/tag/1.3.0).
